# if you want separate pihole and unbound docker containers since the combo doesn't update pihole as often as pihole updates their own container
# you can build a new stack using portainer with this as well

version: '2.1'

volumes:
  pihole:
  dnsmasq:

services:
  pihole:
    image: pihole/pihole:latest
    privileged: true
    volumes:
      - 'pihole:/etc/pihole'
      - 'dnsmasq:/etc/dnsmasq.d'
    dns:
      - '127.0.0.1'
    network_mode: host
    environment:
      - 'ServerIP=${IP ADD}'
      - 'TZ=America/New_York'
      - 'DNS1=127.0.0.1#5053'
      - 'DNS2=127.0.0.1#5053'
      - 'INTERFACE=eth0'
      - 'DNSMASQ_LISTENING=eth0'
  unbound:
    image: klutchell/unbound
    ports:
      - '5053:5053/udp'
