version: '3.3'


services:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    hostname: pihole
    domainname: pihole.local
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 80/tcp
      #- 67/tcp   if you wish to use Pihole as your DHCP server. Extra steps will be required and are easy to follow
      # from the pihole website. Please read through their tutorial before running docker-compose.  https://docs.pi-hole.net/docker/DHCP/
    environment:
      ServerIP: "IP Address"	#IP address of server
#      TZ: America/New_York  #your timezone
#      WEBPASSWORD: WEB_PASS #your password. Optional
      DNS1: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNS2: 127.0.0.1#5335 # Hardcoded to our Unbound server
      DNSSEC: "true" # Enable DNSSEC
    network_mode: "host"
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      #these "volumes" will be placed in the directory from which you are running the docker commands. You can edit them to your preferred directory if you wish
    restart: unless-stopped
